language: objective-c

xcode_project: safeslingerdemo/safeslingerdemo.xcodeproj
xcode_scheme: safeslingerdemo/safeslingerdemo
script:
  - xcodebuild -project safeslingerdemo/safeslingerdemo.xcodeproj -scheme exchangeui -sdk iphonesimulator build
  - xcodebuild -project safeslingerdemo/safeslingerdemo.xcodeproj -scheme safeslingerexchange -sdk iphonesimulator build
  - xcodebuild -project safeslingerdemo/safeslingerdemo.xcodeproj -scheme safeslingerdemo -sdk iphonesimulator build

